/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioGenerateRouteImport } from './routes/studio.generate'
import { Route as StudioImportRouteImport } from './routes/studio.import'
import { Route as StudioJobsRouteImport } from './routes/studio.jobs'
import { Route as StudioLibraryRouteImport } from './routes/studio.library'
import { Route as StudioModelRouteImport } from './routes/studio.model'
import { Route as StudioVideoRouteImport } from './routes/studio.video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioGenerateRoute = StudioGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => StudioRoute,
} as any)
const StudioImportRoute = StudioImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => StudioRoute,
} as any)
const StudioJobsRoute = StudioJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLibraryRoute = StudioLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => StudioRoute,
} as any)
const StudioModelRoute = StudioModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => StudioRoute,
} as any)
const StudioVideoRoute = StudioVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/generate': typeof StudioGenerateRoute
  '/studio/import': typeof StudioImportRoute
  '/studio/jobs': typeof StudioJobsRoute
  '/studio/library': typeof StudioLibraryRoute
  '/studio/model': typeof StudioModelRoute
  '/studio/video': typeof StudioVideoRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio/generate': typeof StudioGenerateRoute
  '/studio/import': typeof StudioImportRoute
  '/studio/jobs': typeof StudioJobsRoute
  '/studio/library': typeof StudioLibraryRoute
  '/studio/model': typeof StudioModelRoute
  '/studio/video': typeof StudioVideoRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/generate': typeof StudioGenerateRoute
  '/studio/import': typeof StudioImportRoute
  '/studio/jobs': typeof StudioJobsRoute
  '/studio/library': typeof StudioLibraryRoute
  '/studio/model': typeof StudioModelRoute
  '/studio/video': typeof StudioVideoRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/studio/generate'
    | '/studio/import'
    | '/studio/jobs'
    | '/studio/library'
    | '/studio/model'
    | '/studio/video'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/studio/generate'
    | '/studio/import'
    | '/studio/jobs'
    | '/studio/library'
    | '/studio/model'
    | '/studio/video'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/studio/generate'
    | '/studio/import'
    | '/studio/jobs'
    | '/studio/library'
    | '/studio/model'
    | '/studio/video'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/generate': {
      id: '/studio/generate'
      path: '/generate'
      fullPath: '/studio/generate'
      preLoaderRoute: typeof StudioGenerateRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/import': {
      id: '/studio/import'
      path: '/import'
      fullPath: '/studio/import'
      preLoaderRoute: typeof StudioImportRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/jobs': {
      id: '/studio/jobs'
      path: '/jobs'
      fullPath: '/studio/jobs'
      preLoaderRoute: typeof StudioJobsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/library': {
      id: '/studio/library'
      path: '/library'
      fullPath: '/studio/library'
      preLoaderRoute: typeof StudioLibraryRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/model': {
      id: '/studio/model'
      path: '/model'
      fullPath: '/studio/model'
      preLoaderRoute: typeof StudioModelRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/video': {
      id: '/studio/video'
      path: '/video'
      fullPath: '/studio/video'
      preLoaderRoute: typeof StudioVideoRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface StudioRouteChildren {
  StudioGenerateRoute: typeof StudioGenerateRoute
  StudioImportRoute: typeof StudioImportRoute
  StudioJobsRoute: typeof StudioJobsRoute
  StudioLibraryRoute: typeof StudioLibraryRoute
  StudioModelRoute: typeof StudioModelRoute
  StudioVideoRoute: typeof StudioVideoRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioGenerateRoute: StudioGenerateRoute,
  StudioImportRoute: StudioImportRoute,
  StudioJobsRoute: StudioJobsRoute,
  StudioLibraryRoute: StudioLibraryRoute,
  StudioModelRoute: StudioModelRoute,
  StudioVideoRoute: StudioVideoRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
